### GET request ping
GET http://localhost:8082/api/ping
Accept: application/json
Authorization: Basic X2VzbF9pbnRlcm5hbF93czpfZXNsX2ludGVybmFsX3dz

### GET request list
GET http://localhost:8082/api/listUserActivity?fromTs=2023-01-01T08:12:01.292&toTs=2023-12-31T08:12:01.292
Accept: application/json
Content-Type: application/json
Authorization: Basic X2VzbF9pbnRlcm5hbF93czpfZXNsX2ludGVybmFsX3dz


### Send POST request add
POST http://localhost:8082/api/logUserActivity
Content-Type: application/json
Authorization: Basic X2VzbF9pbnRlcm5hbF93czpfZXNsX2ludGVybmFsX3dz

{
  "eventId": "666666",
  "token": "0089402-1de8-4c86-847d-1da57c3878da",
  "clientId": "Imre",
  "channelId": "GEORGE_WEB",
  "appId": "Intellij",
  "activityCode": "TEST",
  "resultCode": "OK",
  "timeStamp": "2023-08-10T08:12:01.292Z",
  "correlationId": "1",
  "category": "TEST",
  "textParams": "1234,5567",
  "logLevel": "INFO"
}

### Send DELETE request user_activity_log
DELETE http://localhost:9200/user_activity_log

###
GET http://localhost:9200/user_activity_log/_count

###
GET http://localhost:9200/user_activity_log/_count?q=id:ac207b0a-63c7-4281-a0ef-f37f048c2532

