spring:
  jpa:
    open-in-view: false
  devtools:
    add-properties: true
  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG